### ISSUE TITLE
Cannot connect to elasticache

### ISSUE THREAD

**Issue by batbayar-su** [ktheory/dalli-elasticache#18]
This error shows on run application on passenger

These are the possible causes:
There may be a syntax error in the application's code. Please check for such errors and fix them.
A required library may not installed. Please install all libraries that this application requires.
The application may not be properly configured. Please check whether all configuration files are written correctly, fix any incorrect configurations, and restart this application.
A service that the application relies on (such as the database server or the Ferret search engine server) may not have been started. Please start that service.
Further information about the error may have been written to the application's log file. Please check it in order to analyse the problem.
Error message:
getaddrinfo: Name or service not known
Exception class:
SocketError

**Comment by AmitPatel-BoTreeConsulting** [comment]
I faced the same issue while deploying Rails 4.2 application using Capistrano. Thanks @yozlet your suggestion worked.

I have been using memcached for cache store.

**production.rb**

```
elasticache = Dalli::ElastiCache.new('memcahced-autodiscovery.cache.amazonaws.com:11211')
config.cache_store = :dalli_store, elasticache.servers
```
