### ISSUE TITLE
Is it pure memcached compatible?

### ISSUE THREAD

**Issue by icalvete** [ktheory/dalli-elasticache#35]
I'm testing this gem with memcached with this simple script

```ruby
#!/usr/bin/env ruby                                                             

require 'dalli-elasticache'


endpoint    = "localhost:11211"
elasticache = Dalli::ElastiCache.new(endpoint)

#puts elasticache.public_methods

elasticache.set('test_key', 'test_value')

puts elasticache.get('test_key')                         
```

I got this...

```
vagrant@ror:~$ ./test.rb 
Traceback (most recent call last):
./test.rb:11:in `<main>': undefined method `set' for #<Dalli::ElastiCache:0x00005556b58a7990> (NoMethodError)
Did you mean?  send
```

I'm doing something wrong?

I'm using those versions:

dalli (3.2.0)
dalli-elasticache (0.2.0)

Thanks.

**Comment by petergoldstein** [comment]
@icalvete In the situation you describe `dalli-elasticache` is not required or advised.  This gem is used to resolve the individual node addresses for an ElastiCache memcached cluster, so it can be used by `dalli` (or in theory anything else that needs those addresses).  It is not a proxy for the `Dalli::Client` class.

For the example you give above, you should just use Dalli:

```
#!/usr/bin/env ruby                                                             

require 'dalli'

endpoint    = "localhost:11211"
client = Dalli::Client.new(endpoint)

client.set('test_key', 'test_value')
puts client.get('test_key')      
```

**Comment by icalvete** [comment]
@petergoldstein I want my code compatible with both, memchached or elasticache.

Thats why I'm trying this. The decision to use Elasticache it is not made yet.

**Comment by petergoldstein** [comment]
@icalvete If you want to support both local (or just unclustered remote) and Elasticache, you will need to control that using some sort of variable.  You will not be able to do this transparently because you're working with two different types of servers (cluster configuration endpoints vs memcached servers).

For example:

```
#!/usr/bin/env ruby                                                             

require 'dalli'

servers  = 
  if ENV['USE_ELASTICACHE']
    require 'dalli-elasticache'
    config_endpoint = "example.com:1234"
    Dalli::ElastiCache.new(config_endpoint).servers
  else
     ["localhost:11211"]
  end
client = Dalli::Client.new(servers)

client.set('test_key', 'test_value')
puts client.get('test_key') 
```
